package com.hero.patterns.behavioral.observer.observers;

import com.hero.patterns.behavioral.observer.ReportObserver;

public class EmailObserver implements ReportObserver {
    private final String emailAddress;

    public EmailObserver(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    @Override
    public void update(String reportName, String reportType, String userId) {
        System.out.println("  [EMAIL] Sending notification to: " + emailAddress);
        System.out.println("  [EMAIL] Subject: Report available - " + reportName);
        System.out.println("  [EMAIL] Generated by: " + userId + " | Type: " + reportType);
    }
}
